# Generated by Django 4.2.1 on 2023-05-23 09:33

from django.db import migrations
import sanitizer.models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="details",
            field=sanitizer.models.SanitizedTextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="todo",
            name="task",
            field=sanitizer.models.SanitizedCharField(max_length=200, null=True),
        ),
    ]
