runtime: python39

env_variables:
  APPENGINE_URL: https://python-bugs-1.ew.r.appspot.com

# beta_settings:
#   cloud_sql_instances: python-bugs-1:europe-west1:todo-project

handlers:
- url: /static
  static_dir: static/
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /.*
  script: auto