runtime: python310

env_variables:
  APPENGINE_URL: https://python-bugs-1.ew.r.appspot.com
  INSTANCE_UNIX_SOCKET: /cloudsql/python-bugs-1:europe-west1:todo-project
  DB_USER: todo_user
  DB_PASS: todo_admin1234
  DB_NAME: todo-db-1

# beta_settings:
#   cloud_sql_instances: python-bugs-1:europe-west1:todo-project=tcp:5432

handlers:
- url: /static
  static_dir: static/
  # http_headers:
  #   Access-Control-Allow-Origin: "*"

- url: /.*
  script: auto
  